require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe TableContentsController, :type => :controller do

  before do
    @book = FactoryGirl.create(:book)
  end
  
  # This should return the minimal set of attributes required to create a valid
  # TableContent. As you add validations to TableContent, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {content: 'tests content', level: 1, order: 1, book_id: @book.id}
  }

  let(:invalid_attributes) {
    {description: 'tests content'}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TableContentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }
  
  describe "GET index" do
    it "assigns all table_contents as @table_contents" do
      table_content = TableContent.create! valid_attributes
      get :index, {:book_id => @book.id}, valid_session
      expect(assigns(:table_contents)).to eq([table_content])
    end
  end

  describe "GET show" do
    it "assigns the requested table_content as @table_content" do
      table_content = TableContent.create! valid_attributes
      get :show, {:id => table_content.to_param, :book_id => @book.id}, valid_session
      expect(assigns(:table_content)).to eq(table_content)
    end
  end

  describe "GET new" do
    it "assigns a new table_content as @table_content" do
      get :new, {:book_id => @book.id}, valid_session
      expect(assigns(:table_content)).to be_a_new(TableContent)
    end
  end

  describe "GET edit" do
    it "assigns the requested table_content as @table_content" do
      table_content = TableContent.create! valid_attributes
      get :edit, {:id => table_content.to_param, :book_id => @book.id}, valid_session
      expect(assigns(:table_content)).to eq(table_content)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TableContent" do
        expect {
          post :create, {:table_content => valid_attributes, :book_id => @book.id}, valid_session
        }.to change(TableContent, :count).by(1)
      end

      it "assigns a newly created table_content as @table_content" do
        post :create, {:table_content => valid_attributes, :book_id => @book.id}, valid_session
        expect(assigns(:table_content)).to be_a(TableContent)
        expect(assigns(:table_content)).to be_persisted
      end

      it "redirects to the created table_content" do
        post :create, {:table_content => valid_attributes, :book_id => @book.id}, valid_session
        expect(response).to redirect_to(book_table_contents_path(@book))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved table_content as @table_content" do
        post :create, {:table_content => invalid_attributes, :book_id => @book.id}, valid_session
        expect(assigns(:table_content)).to be_a_new(TableContent)
      end

      it "re-renders the 'new' template" do
        post :create, {:table_content => invalid_attributes, :book_id => @book.id}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    
    describe "with valid params" do
      let(:new_attributes) {
        {content: 'New content', level: 2, order: 2, book_id: @book.id}
      }

      it "updates the requested table_content" do
        table_content = TableContent.create! valid_attributes
        put :update, {:id => table_content.to_param, :table_content => new_attributes, :book_id => @book.id}, valid_session
        table_content.reload
        expect(assigns(:table_content)).to eq(table_content)
      end

      it "assigns the requested table_content as @table_content" do
        table_content = TableContent.create! valid_attributes
        put :update, {:id => table_content.to_param, :table_content => valid_attributes, :book_id => @book.id}, valid_session
        expect(assigns(:table_content)).to eq(table_content)
      end

      it "redirects to the table_content" do
        table_content = TableContent.create! valid_attributes
        put :update, {:id => table_content.to_param, :table_content => valid_attributes, :book_id => @book.id}, valid_session
        expect(response).to redirect_to(book_table_contents_path(@book))
      end
    end

    describe "with invalid params" do
      it "assigns the table_content as @table_content" do
        table_content = TableContent.create! valid_attributes
        put :update, {:id => table_content.to_param, :table_content => invalid_attributes, :book_id => @book.id}, valid_session
        expect(assigns(:table_content)).to eq(table_content)
      end

      it "re-renders the 'edit' template" do
        table_content = TableContent.create! valid_attributes
        put :update, {:id => table_content.to_param, :table_content => invalid_attributes, :book_id => @book.id}, valid_session
        #expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested table_content" do
      table_content = TableContent.create! valid_attributes
      expect {
        delete :destroy, {:id => table_content.to_param, :book_id => @book.id}, valid_session
      }.to change(TableContent, :count).by(-1)
    end

    it "redirects to the table_contents list" do
      table_content = TableContent.create! valid_attributes
      delete :destroy, {:id => table_content.to_param, :book_id => @book.id}, valid_session
      expect(response).to redirect_to(book_table_contents_path(@book))
    end
  end

end
